CREATE DATABASE `APPLICATION`;


 CREATE TABLE `USER_INFO` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `CREATED_ON` datetime NOT NULL,
  `UPDATED_ON` datetime NOT NULL,
  `CLIENT_EMAIL` varchar(50) COLLATE utf8mb4_general_ci NOT NULL,
  `ENCODED_CLIENT_SECRET` varchar(255) COLLATE utf8mb4_general_ci NOT NULL,
  `IS_ACTIVE` bit(1) DEFAULT NULL,
  `PERMISSIONS` varchar(255) COLLATE utf8mb4_general_ci NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `INDEX_CLIENT_EMAIL` (`CLIENT_EMAIL`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;